# Generated by Django 6.0.4 on 2026-04-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
            preserve_default=False,
        ),
    ]
